// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // seed: команда для заполнения БД тестовыми данными
    seed: "ts-node --transpile-only prisma/seed.ts",
  },
  datasource: {
    // URL подключения к PostgreSQL из переменной окружения
    url: process.env["DATABASE_URL"],
  },
});
