[build]
builder = "nixpacks"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start:prod"
healthcheckPath = "/api/docs"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
